Complete FileTypeDetectionController Tests
k8-proxy/cs-k8s-api pull request #399
Opened 2021-06-24 08:14 UTC by ggrig

2021-06-25 09:42 UTC, mohitsengarr requested changes
We should follow the C# coding conventions for class name, it's properties, functions etc.

2021-06-25 09:42 UTC, mohitsengarr commented on Source/Service/Controllers/AnalyseController.cs
> +                if (null == request)
I think this check isn't required because if request is null control never comes inside AnalyseFromBase64 function.

2021-06-25 09:42 UTC, mohitsengarr commented on Source/Service/Controllers/AnalyseController.cs
> +                if (null == file)
We already have `if (!_fileUtility.TryGetBase64File(request.Base64, out byte[] file))`, still we need this check?

2021-06-25 09:42 UTC, mohitsengarr commented on Source/Service/Controllers/AnalyseController.cs
> +                if (null == fileId)
we should add this condition with OR operator with `if (fileId == Guid.Empty)`

2021-06-26 04:47 UTC, ggrig commented on Source/Common/Glasswall.CloudProxy.Common/Web/Abstraction/CloudProxyController.cs
> +                return _testTransactionStorePath;
It does not - the property returns the same Constants.TRANSACTION_STORE_PATH value as was previously used for regular workflow. The change is about to utilize an alternative path for the test case.

2021-06-26 04:52 UTC, ggrig commented on Source/Service/Controllers/AnalyseController.cs
> +                if (null == request)
In unit tests, there are no requests at all. This has been done to handle those cases.

2021-06-26 05:04 UTC, ggrig commented on Source/Service/Controllers/AnalyseController.cs
> +                if (null == file)
This was added to handle null case separately
See https://hackernoon.com/c-parameter-null-validation-explained-9h113uca for a detailed explanation of why this is needed

2021-06-26 05:04 UTC, ggrig commented on Source/Common/Glasswall.CloudProxy.Common/Web/Abstraction/CloudProxyController.cs
> +                string default_path = Constants.TRANSACTION_STORE_PATH;
OK

2021-06-26 05:08 UTC, ggrig commented on Source/Service/Controllers/AnalyseController.cs
> +                if (null == fileId)
Adding it with separate blocks allows handling those more granularly and produces different error messages.
When the issue occurs with the OR condition you will be guessing which of the conditions caused it. 
This way you get the exact message of what the issue is.

2021-06-26 11:48 UTC, mohitsengarr commented on Source/Service/Controllers/AnalyseController.cs
> +                if (null == request)
Ok, but for a user this will never null at this line. we already annotated this parameter as required.

2021-06-26 11:48 UTC, mohitsengarr approved these changes

2021-06-26 12:34 UTC, mohitsengarr commented
@ggrig Could you please resolve the conflicts?

2021-06-28 09:37 UTC, merged