Unit tests
k8-proxy/cs-k8s-api pull request #428
Opened 2021-06-29 12:44 UTC by ggrig

97 tests testing all the controllers

![image](https://user-images.githubusercontent.com/26714598/123799401-3e620680-d8f9-11eb-9f35-6d2dca744f7b.png)

2021-06-29 13:26 UTC, mohitsengarr requested changes

2021-06-29 13:26 UTC, mohitsengarr commented on Source/Service/Controllers/RebuildController.cs
> +                    System.IO.File.WriteAllBytes(protectedZipFilePath, fileBytes);
please use the Async version of it. WriteAllBytesAsync

2021-06-29 13:26 UTC, mohitsengarr commented on Source/Service/Controllers/RebuildController.cs
> +                    // The following fails to create a file
I don't understand why it is failing for you as it is already working. However, can you please remove the commented code.

2021-06-30 06:22 UTC, ggrig commented on Source/Service/Controllers/RebuildController.cs
> +                    // The following fails to create a file
I also do not have a good explanation. It seems this relates to the utilization of a Mock object for  IFormFile. The observation is that once created and read it does not allow a second read.

2021-06-30 07:02 UTC, ggrig commented on Source/Service/Controllers/RebuildController.cs
> +                    System.IO.File.WriteAllBytes(protectedZipFilePath, fileBytes);
Done. Thanks for pointing that out

2021-06-30 07:44 UTC, mohitsengarr approved these changes

2021-06-30 11:09 UTC, merged