Swagger updates - issue 471
k8-proxy/cs-k8s-api pull request #481
Opened 2021-07-14 07:35 UTC by ggrig

The PR addresses #471

2021-07-14 13:08 UTC, GINAGC commented
@ggrig please list the updates made on this PR. Can you also attach the before and after of the swagger page (at high level).

2021-07-14 13:09 UTC, GINAGC requested changes
Since many updates were done in the file, please provide a high level summary of the updates.

2021-07-15 10:34 UTC, ggrig commented
@GINAGC 
I have updated the comments to reflect the changes made there

2021-07-15 11:20 UTC, GINAGC approved these changes

2021-07-15 11:20 UTC, merged